# Generated by Django 5.2.6 on 2025-12-22 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MapSearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_ID', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=20)),
                ('region', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=15)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('waiting', models.IntegerField()),
            ],
        ),
    ]
