# Generated by Django 5.2.6 on 2025-12-22 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('restaurant_ID', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='레스토랑 ID')),
                ('name', models.CharField(max_length=200, verbose_name='레스토랑 이름')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='전화번호')),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='평점')),
                ('category', models.CharField(blank=True, max_length=20, verbose_name='카테고리')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='주소')),
                ('image_url', models.URLField(blank=True, max_length=500, verbose_name='이미지 URL')),
                ('x', models.FloatField(blank=True, null=True, verbose_name='경도')),
                ('y', models.FloatField(blank=True, null=True, verbose_name='위도')),
                ('region', models.CharField(blank=True, max_length=20, verbose_name='지역')),
                ('city', models.CharField(blank=True, max_length=15, verbose_name='도시')),
                ('waiting', models.IntegerField(blank=True, null=True, verbose_name='대기 인원')),
                ('rec_quality', models.FloatField(blank=True, null=True, verbose_name='추천 품질 점수')),
                ('rec_balanced', models.FloatField(blank=True, null=True, verbose_name='추천 균형 점수')),
                ('rec_convenience', models.FloatField(blank=True, null=True, verbose_name='추천 편의 점수')),
            ],
            options={
                'verbose_name': '레스토랑',
                'verbose_name_plural': '레스토랑',
            },
        ),
    ]
