# Generated by Django 5.2.6 on 2025-12-19 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_ID', models.IntegerField(null=True, unique=True, verbose_name='레스토랑 ID')),
                ('name', models.CharField(max_length=200, verbose_name='레스토랑 이름')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='전화번호')),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='평점')),
                ('category', models.CharField(blank=True, max_length=20, verbose_name='카테고리')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='주소')),
                ('image_url', models.URLField(blank=True, max_length=500, verbose_name='이미지 URL')),
                ('x', models.FloatField(blank=True, null=True, verbose_name='경도')),
                ('y', models.FloatField(blank=True, null=True, verbose_name='위도')),
                ('region', models.CharField(blank=True, max_length=20, verbose_name='지역')),
                ('city', models.CharField(blank=True, max_length=15, verbose_name='도시')),
                ('waitting', models.IntegerField(blank=True, null=True, verbose_name='대기 인원')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '레스토랑',
                'verbose_name_plural': '레스토랑',
                'ordering': ['-created_at'],
            },
        ),
    ]
