# Generated by Django 5.2.6 on 2025-12-15 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='restaurant_id',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='address',
            field=models.CharField(blank=True, max_length=200, verbose_name='주소'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='category',
            field=models.CharField(blank=True, max_length=20, verbose_name='카테고리'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_ID',
            field=models.IntegerField(default=2, unique=True, verbose_name='레스토랑 ID'),
            preserve_default=False,
        ),
    ]
