# Generated by Django 5.2.6 on 2025-12-15 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_restaurant_restaurant_id_restaurant_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_ID',
            field=models.IntegerField(null=True, unique=True, verbose_name='레스토랑 ID'),
        ),
    ]
