# Generated by Django 5.2.6 on 2025-12-15 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_restaurant_restaurant_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='city',
            field=models.CharField(blank=True, max_length=15, verbose_name='도시'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='region',
            field=models.CharField(blank=True, max_length=20, verbose_name='지역'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='x',
            field=models.FloatField(blank=True, null=True, verbose_name='경도'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='y',
            field=models.FloatField(blank=True, null=True, verbose_name='위도'),
        ),
    ]
