# Generated by Django 5.2.6 on 2025-12-16 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_restaurant_city_restaurant_region_restaurant_x_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='waitting',
            field=models.IntegerField(blank=True, null=True, verbose_name='대기 인원'),
        ),
    ]
