# Generated by Django 5.2.6 on 2025-12-19 09:00

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmbeddedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('rating', models.FloatField(default=0.0)),
                ('review_count', models.IntegerField(default=0)),
                ('blog_count', models.IntegerField(default=0)),
                ('place_url', models.URLField(blank=True)),
                ('img_url', models.URLField(blank=True, max_length=500)),
                ('x', models.FloatField(blank=True, null=True)),
                ('y', models.FloatField(blank=True, null=True)),
                ('location', models.CharField(max_length=50)),
                ('hourly_visit', models.TextField(blank=True, default='')),
                ('description', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=768)),
                ('current_waiting_team', models.IntegerField(default=0)),
                ('estimated_waiting_time', models.IntegerField(default=0)),
            ],
        ),
    ]
