# Generated by Django 5.2.6 on 2025-12-19 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RAG', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            """
            ALTER TABLE "RAG_embeddeddata"
            ADD COLUMN IF NOT EXISTS "estimated_waiting_time" integer NOT NULL DEFAULT 0
            """,
            reverse_sql="""
            ALTER TABLE "RAG_embeddeddata"
            DROP COLUMN IF EXISTS "estimated_waiting_time"
            """,
        ),
    ]
