# Generated by Django 5.2.6 on 2025-12-19 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RAG', '0002_fix_estimated_waiting_time'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE "RAG_embeddeddata"
                ALTER COLUMN "average_waiting_time" SET DEFAULT 0;

                UPDATE "RAG_embeddeddata"
                SET "average_waiting_time" = 0
                WHERE "average_waiting_time" IS NULL;
            """,
            reverse_sql="""
                ALTER TABLE "RAG_embeddeddata"
                ALTER COLUMN "average_waiting_time" DROP DEFAULT;
            """,
        ),
    ]
